config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "bank_billets#index"

  resources :bank_billets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank_billet.rb
class BankBillet < ApplicationRecord
  validates :amount, :expire_at, :customer_person_name, :customer_cnpj_cpf, presence: true
  validates :customer_state, :customer_city_name, :customer_zipcode, presence: true
  validates :customer_address, :customer_address_neighborhood, presence: true

  enum status: { opened: 0, canceled: 1, paid: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bank_billets_controller.rb
class BankBilletsController < ApplicationController
  before_action :set_bank_billet, only: [:show, :update, :edit, :destroy]
  
  def index
    @bank_billets = BankBillet.all
  end

  def show
    @bank_billet_details = KobanaService.new(@bank_billet).find_bank_billet
  end

  def new
    @bank_billet = BankBillet.new
  end

  def create
    @bank_billet = BankBillet.new(bank_billet_params)

    if @bank_billet.save
      KobanaService.new(@bank_billet).create_bank_billet

      flash[:success] = "Object successfully created"
      redirect_to @bank_billet
    else
      flash[:error] = "Something went wrong"
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    @bank_billet = BankBillet.find(params[:id])
  end

  def update
    if @bank_billet.update(bank_billet_params)
      redirect_to @bank_billet
    else
      render json: @bank_billet.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @bank_billet.canceled!
      KobanaService.new(@bank_billet).cancel_bank_billet
      flash[:success] = "Boleto cancelado"
      redirect_to root_path, status: :see_other
    else
      flash[:error] = "Something went wrong"
      render :show
    end
  end

  private

  def set_bank_billet
    @bank_billet = BankBillet.find(params[:id])
  end

  def bank_billet_params
    params.require(:bank_billet).permit(:amount, :expire_at, :customer_person_name, :customer_cnpj_cpf, :customer_state,
                                         :customer_city_name, :customer_zipcode, 
                                         :customer_address, :customer_address_neighborhood)
  end
end
    

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(date)
    return if date.blank?
    
    Date.parse(date.to_s).strftime('%d/%m/%Y')
  end
end

app/views/bank_billets/_form.html.erb
<div class="container">
  <% if bank_billet.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% bank_billet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: bank_billet, class: "row" do |form| %>
    <div class="col-sm-6">
      <%= form.label :amount %><br>
      <%= form.number_field :amount, class: "w-100" %>
    </div>

    <div class="col-md-6">
      <%= form.label :expire_at %><br>
      <%= form.date_field :expire_at, class: "w-100" %><br>
    </div>

    <div class="col-md-6">
      <%= form.label :customer_person_name %><br>
      <%= form.text_field :customer_person_name, class: "w-100" %><br>
    </div><br>

    <div class="col-md-6">
      <%= form.label :customer_cnpj_cpf %><br>
      <%= form.text_field :customer_cnpj_cpf, class: "w-100" %><br>
    </div>

    <div class="col-md-6">
      <%= form.label :customer_state %><br>
      <%= form.text_field :customer_state, class: "w-100" %><br>
    </div>

    <div class="col-md-6">
      <%= form.label :customer_city_name %><br>
      <%= form.text_field :customer_city_name, class: "w-100" %><br>
    </div>

    <div class="col-md-6">
      <%= form.label :customer_zipcode %><br>
      <%= form.text_field :customer_zipcode, class: "w-100" %><br>
    </div>

    <div class="col-md-6">
      <%= form.label :customer_address %><br>
      <%= form.text_field :customer_address, class: "w-100" %><br>
    </div>

    <div class="col-md-6">
      <%= form.label :customer_address_neighborhood %><br>
      <%= form.text_field :customer_address_neighborhood, class: "w-100" %><br>
    </div>

    <div class="col-md-12 mt-3">
      <div class="btn btn-success mr-2 p-0">
        <%= form.submit class: "btn" %>
      </div>
      
    </div>
  <% end %>
</div>

app/views/bank_billets/_nav.html.erb
<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="/">Kobana Challenge</a>
    <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="/">Boletos</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/bank_billets/edit.html.erb
<h3>Editar Boleto Bancário</h3>

<%= render 'form', bank_billet: @bank_billet  %>

app/views/bank_billets/index.html.erb
<section class="jumbotron text-center col-md-12">
  <div class="container">
    <h1 class="jumbotron-heading mt-5">Bem-vindo ao Gerenciador de Boletos</h1>
    <p class="lead text-muted">Visualize, Crie, Edite e Exclua seus Boletos Bancários</p>

    <h1>Boletos Bancários</h1>

    <div class="row">
      <% @bank_billets.each do |bank_billet| %>
        <div class="col-sm-6 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= bank_billet.customer_person_name %></h5>
              <p class="card-text"><span class="badge badge-<%= bank_billet.status %>"><%= bank_billet.status %></p></span>
              <p class="card-text">Valor: <%= number_to_currency bank_billet.amount %></p>
              <p class="card-text">Vencimento: <%= formatted_date(bank_billet.expire_at) %></p>
              <div class="btn btn-primary">
                <%= link_to 'Detalhes', bank_billet, :class=>"btn" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="btn btn-primary mb-5">
      <%= link_to 'Criar novo Boleto Bancário', new_bank_billet_path, :class => "btn" %>
    </div>
  </div>

</section>

app/views/bank_billets/new.html.erb
<h3>Crie um Boleto Bancário</h3>
<%= render 'form', bank_billet: @bank_billet  %>

app/views/bank_billets/show.html.erb
<section class="jumbotron text-left col-md-12">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <h3 class="jumbotron-heading mt-5 mb-3">Detalhes do Boleto</h3>
      </div>
      <div class="col-6 mt-4">
        <% if @bank_billet_details["formats"].present? %>
          <div class="btn btn-success mr-2 p-0">
            <%= link_to 'Visualizar Boleto', @bank_billet_details["formats"]["pdf"], class: "btn", target: :blank %>
          </div>
        <% end %>

        <div class="btn btn-info mr-2 p-0">
          <%= link_to 'Alterar', edit_bank_billet_path(@bank_billet), class: "btn" %>
        </div>

        <div class="btn btn-danger mr-2 p-0">
          <%= link_to "Cancelar", bank_billet_path(@bank_billet), data: {
                              turbo_method: :delete,
                              turbo_confirm: "Você tem certeza?"
                            }, class: "btn" %>
        </div>

        <div class="btn btn-secondary mr-2 p-0">
          <%= link_to 'Voltar', bank_billets_path, class: "btn" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-6">
        <div class="card">
          <h5 class="card-header">Beneficiário: <%= @bank_billet_details['beneficiary_name'] %></h5>
          <div class="card-body text-left">
            <p class="card-text">Situação: <span class="badge badge-<%= @bank_billet.status %>"><%= @bank_billet_details['status'] %></p></span>
            <p class="card-text">ID Kobana: <%= @bank_billet_details['id']%></p>
            <p class="card-text">Valor: <%= number_to_currency @bank_billet_details['amount']%></p>
            <p class="card-text">Vencimento: <%= formatted_date(@bank_billet_details['expire_at']) %></p>
            <p class="card-text">Nosso Número: <%= @bank_billet_details['processed_our_number_raw']%></p>
            <p class="card-text">Data de emissão: <%= formatted_date(@bank_billet_details['created_at']) %></p>
            <p class="card-text">Data do Pagamento: <%= formatted_date(@bank_billet_details['paid_at']) %></p>
          </div>
        </div>
      </div>

      <div class="col-6">
        <div class="card">
          <h5 class="card-header">Pagador: <%= @bank_billet.customer_person_name %></h5>
          <div class="card-body text-left">
            <p class="card-text">Quantia: <%= @bank_billet.amount %></p>
            <p class="card-text">CNPJ/CPF: <%= @bank_billet.customer_cnpj_cpf %></p>
            <p class="card-text">Estado: <%= @bank_billet.customer_state %></p>
          <p class="card-text">Cidade: <%= @bank_billet.customer_city_name %></p>
          <p class="card-text">CEP<%= @bank_billet.customer_zipcode %></p>
          <p class="card-text">Endereço: <%= @bank_billet.customer_address %></p>
          <p class="card-text">Bairro: <%= @bank_billet.customer_address_neighborhood %></p>
        </div>
      </div>
    </div>
  </div>  
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'nav', bank_billet: @bank_billet  %>

    <div class="container mt-5 pt-5">
      <%= yield %>
    </div>

  </body>
</html>